### ISSUE TITLE
Strange regression: incompatible types for (mySocket) is (null): TCPConnection and typeof(null) 

### ISSUE THREAD

**Issue by Abscissa** [vibe-d/vibe.d#2108]
```
import vibe.core.net;
TCPConnection mySocket;

void main() {
    auto b = mySocket is null;
}
```

That works on v0.8.2 and v0.8.3-alpha.1. But on v0.8.3-rc.1 it results in:

```
Error: incompatible types for (mySocket) is (null): TCPConnection and typeof(null)
```

**Comment by s-ludwig** [comment]
This is due to the switch to vibe-core, which defines most streams as structs instead of classes/interfaces. This avoids the virtual dispatch that is otherwise necessary and also enables storing the object itself together with the low level event destriptor specific data in eventcore. The latter means zero allocation overhead and the highest possible cache efficiency.

`opCast!bool` is defined so that the code can be changed to `!!mySocket` and still work for both the old and the new implementation.

**Comment by Abscissa** [comment]
Ok, I see, thanks. I guess this can be closed now.
