### PR TITLE
Allow `const` parameters in REST generator

### PR DESCRIPTION
**Pull request by omerfirmak**
This also allows `in` parameters to be used with
`--preview=in`.

### CODE REVIEW

**Comment by Geod24** [comment]
Casting `const` away is not the right approach. Rather, mutability should not be required.
To do this, the value have to be constructed in one go, not piece-meal. That's for example why our deserializer does this:
https://github.com/bosagora/serialization/blob/8f1e4c124e7c909e7b65ffea39e996fc116ba181/source/agora/serialization/Serializer.d#L691-L699

The `staticMap` means we end up calling the constructor, and give it function calls as parameter.
Another "nice" trick is how we deal with static arrays: https://github.com/bosagora/serialization/blob/8f1e4c124e7c909e7b65ffea39e996fc116ba181/source/agora/serialization/Serializer.d#L609-L617

Nowhere in the serializer do we have away `const`ness (we do have `cast`, but they never remove `const`). While `cast`ing away constness is sometimes okay, modifying the underlying data (which this does) never is.

**Comment by omerfirmak** [comment]
Updated

File: web/vibe/web/rest.d [hunk 1]
```diff
@@ -1603,8 +1604,8 @@ private HTTPServerRequestDelegate jsonMethodHandler(alias Func, size_t ridx, T)(
 		{
 			handleCors();
 			foreach (i, P; PTypes) {
-				static if (sroute.parameters[i].isOut) {
-					static assert (sroute.parameters[i].kind == ParameterKind.header);
+				static if (sroute.parameters[i].isOut &&
+					sroute.parameters[i].kind == ParameterKind.header) {
```
Comment (Geod24) [inline web/vibe/web/rest.d:1608]: Why ?

**Comment by Geod24** [comment]
Test plz

File: web/vibe/web/rest.d (hunk 1 above)
Comment (omerfirmak) [reply web/vibe/web/rest.d:1608]: https://github.com/vibe-d/vibe.d/blob/f1554380fefa186298d930eaeccf6f439924ff47/web/vibe/web/internal/rest/common.d#L298-L306

`in`parameters that are passed by reference are marked as `isOut`and end up in the body not header.

File: web/vibe/web/rest.d [hunk 2]
```diff
@@ -1447,7 +1448,7 @@ private HTTPServerRequestDelegate jsonMethodHandler(alias Func, size_t ridx, T)(
 	import vibe.textfilter.urlencode : urlDecode;
 
 	enum Method = __traits(identifier, Func);
-	alias PTypes = ParameterTypeTuple!Func;
+	alias PTypes = staticMap!(Unqual, ParameterTypeTuple!Func);
```
Comment (Geod24) [inline web/vibe/web/rest.d:1451]: This should come with a comment. From my understanding:

```suggestion
    // We need mutable types for deserialization
	alias PTypes = staticMap!(Unqual, ParameterTypeTuple!Func);
```

However there should probably be a check for immutable or the error messages aren't going to be great.

Comment (omerfirmak) [reply web/vibe/web/rest.d:1451]: immutable params compile fine tho?

File: web/vibe/web/rest.d (hunk 1 above)
Comment (Geod24) [reply web/vibe/web/rest.d:1608]: Maybe fix that bug then ? :D

File: web/vibe/web/rest.d (hunk 2 above)
Comment (Geod24) [reply web/vibe/web/rest.d:1451]: So, mutable does not implicitly converts to its `immutable` counterpart, unless the type has no indirection.
Which means that, by deserializing things as `T`, we can't later bind it to a parameter of type `immutable(T)`.
And currently, IIUC, the error is that we try to modify an `immutable(T)` during deserialization.
If it's not one, it has to be the other. If it's neither, two possibilities:
- We are deserializing in one go and we shouldn't have the error to begin with (or the fix is even more trivial?);
- There is a cast somewhere that breaks the type system;

**Comment by omerfirmak** [comment]
> Test plz

Added

File: web/vibe/web/rest.d (hunk 1 above)
Comment (omerfirmak) [reply web/vibe/web/rest.d:1609]: I am not sure if that can be fixed easily. `const ref` and `in` are indistinguishable by looking at their storage class.

Comment (omerfirmak) [reply web/vibe/web/rest.d:1609]: But since REST only allows `const ref` but not `ref` they cant really be outputs actually.

https://github.com/vibe-d/vibe.d/pull/2495

Comment (Geod24) [reply web/vibe/web/rest.d:1609]: > are indistinguishable by looking at their storage class.

They are, using `ParameterStorageClass`. But it requires a new-ish release (2.094 IIRC)

File: tests/rest/source/app.d [hunk 3]
```diff
@@ -460,6 +460,64 @@ class Example7 : Example7API {
...
+	FooType constFoo (const FooType param);
+
+	FooType constRefFoo (const ref FooType param);
+
+	FooType inFoo (in FooType param);
+
+	FooType immutableFoo (immutable FooType param);
+	struct FooType {
+		int a;
+		string s;
```
Comment (Geod24) [inline tests/rest/source/app.d:480]: Now try with `int[]`

Comment (omerfirmak) [reply tests/rest/source/app.d:473]: Done but this will probably have to wait for the next compiler release to work.

**Comment by Geod24** [comment]
```
web-framework-i18n-example ~master: building configuration "application"...
Compiling Diet HTML template home.dt...
../../web/vibe/web/i18n.d(222,4): Error: `"Missing translation key for en_US; home: This is the internationalization example app."`
../../web/vibe/web/i18n.d(175,24):        called from here: `tr(key, null, 0, context)`
../../web/vibe/web/web.d(340,99):        called from here: `tr(key, context)`
/home/runner/.dub/packages/diet-ng-1.8.0/diet-ng/source/diet/traits.d(75,23):        called from here: `translate(text, context)`
/home/runner/.dub/packages/diet-ng-1.8.0/diet-ng/source/diet/parser.d(1239,17):        called from here: `translate(kln, stripExtension(baseName(loc.file)))`
/home/runner/.dub/packages/diet-ng-1.8.0/diet-ng/source/diet/parser.d(1110,20):        called from here: `parseTextLine(remainder, ret, tmploc)`
/home/runner/.dub/packages/diet-ng-1.8.0/diet-ng/source/diet/parser.d(1044,38):        called from here: `parseTagLine(input, loc, has_nested)`
/home/runner/.dub/packages/diet-ng-1.8.0/diet-ng/source/diet/parser.d(77,76):        called from here: `parseDietRaw(f)`
```

@s-ludwig : Looks like our CI is broken ?

**Comment by Geod24** [comment]
Indeed, it's also triggering in Buildkite: https://github.com/dlang/dmd/pull/12526#issuecomment-888582301

**Comment by PetarKirov** [comment]
@Geod24 I think the cause may have been this PR: https://github.com/rejectedsoftware/diet-ng/pull/92

**Comment by Geod24** [comment]
@omerfirmak : Please rebase

**Comment by omerfirmak** [comment]
Rebased

**Comment by Geod24** [comment]
```
[INFO] Running test rest
+ cd tests/rest
+ dub --compiler=dmd --build-mode=separate
Running pre-generate commands for vibe-d:tls...
Performing "debug" build using dmd for x86_64.
[...]
tests ~master: building configuration "application"...
../../web/vibe/web/rest.d(1609,6): Error: static assert:  `sroute.parameters[0].kind == ParameterKind.header` is false
../../web/vibe/web/rest.d(442,45):        instantiated from here: `jsonMethodHandler!(constRefFoo, 1LU, Example8)`
source/app.d(721,23):        instantiated from here: `registerRestInterface!(Example8)`
dmd failed with exit code 1.
```

**Comment by omerfirmak** [comment]
What, https://github.com/dlang/dmd/pull/12458/commits/23333399783b5d8deb9edcb518c562c91404b833 should've fixed it.

**Comment by Geod24** [comment]
https://github.com/dlang/dmd/commit/03c30609389c5dce7e22ce39e8a176081e3e9c10

Only for v2.096.1 and above (LDC 1.26). So you need to version out the test for anything less than that (we test with 10 versions of DMD). But it also fails on dmd-latest so no luck here.

File: web/vibe/web/internal/rest/common.d [hunk 4]
```diff
@@ -300,7 +301,7 @@ import std.traits : hasUDA;
 					pi.isOut = true;
 				} else static if (SC & ParameterStorageClass.ref_) {
 					pi.isIn = true;
-					pi.isOut = true;
+					pi.isOut = isMutable!PT;
```
Comment (omerfirmak) [inline web/vibe/web/internal/rest/common.d:304]: Let's see if this will help. Works fine on LDC 1.27.0.

Comment (Geod24) [reply web/vibe/web/internal/rest/common.d:304]: Hold on, we use `inIn` for "input parameter", not the `in` storage class, right ? Damn that's confusing :D
