### ISSUE TITLE
regression(vibe 0.8) vibe.data.bson.BsonSerializer.readDictionary is not callable using argument type

### ISSUE THREAD

**Issue by timotheecour** [vibe-d/vibe.d#1991]
app.d:
```
void main(){}

import vibe.data.bson;

class A {
  @property @name("foo") {
    string fooString() const { return "a"; }
    void fooString(string a) {  }
  }
}

void test(){
	Bson a;
  auto a2=a.deserializeBson!A;
}
```

dub.json:
```
{
"name": "test1",
"targetType": "dynamicLibrary",
"targetName": "test1",
"dependencies": {"vibe-d": "==0.8.1",},

"description": "A simple vibe.d server application. v1",
"copyright": "Copyright © 2017, Timothee Cour",
"authors": ["Timothee Cour"],
"license": "proprietary"
}
```

```
/Users/timothee/.dub/packages/vibe-d-0.8.1/vibe-d/data/vibe/data/serialization.d(752): Error: function vibe.data.bson.BsonSerializer.readDictionary!(Traits!(A, DefaultPolicy)).readDictionary (scope void delegate(string) @safe entry_callback) is not callable using argument types (void)
/Users/timothee/.dub/packages/vibe-d-0.8.1/vibe-d/data/vibe/data/serialization.d(565): Error: template instance vibe.data.serialization.deserializeValueImpl!(BsonSerializer, DefaultPolicy).deserializeValueDeduced!(A) error instantiating
/Users/timothee/.dub/packages/vibe-d-0.8.1/vibe-d/data/vibe/data/serialization.d(299):        instantiated from here: deserializeValue!(A)
/Users/timothee/.dub/packages/vibe-d-0.8.1/vibe-d/data/vibe/data/serialization.d(265):        instantiated from here: deserializeWithPolicy!(BsonSerializer, DefaultPolicy, A, Bson)
/Users/timothee/.dub/packages/vibe-d-0.8.1/vibe-d/data/vibe/data/bson.d(1141):        instantiated from here: deserialize!(BsonSerializer, A, Bson)
source/app.d(17):        instantiated from here: deserializeBson!(A)
```

it worked fine with `0.7.32`

NOTE: this syntax was proposed by @s-ludwig here: https://github.com/vibe-d/vibe.d/issues/1710#issuecomment-288877154
