### ISSUE TITLE
Error: cannot implicitly convert expression conn of type TCPConnection to vibe.core.stream.Stream

### ISSUE THREAD

**Issue by Herringway** [vibe-d/vibe.d#2097]
This example fails to compile with DMD 2.079.0 (both linux and windows) and vibe-d 0.8.3-beta.1, though it successfully compiles with vibe-d 0.8.3-alpha.1.

```D
#!/usr/bin/env dub
/+ dub.json:
{
	"dependencies": {
		"vibe-d:core": "0.8.3-beta.1"
	}
}
+/
import vibe.core.net;
import vibe.core.stream;

void main() {}

void bad1() {
	auto conn = connectTCP("localhost", 12345);
	Stream x;
	x = conn;
}
void bad2() {
	auto conn = connectTCP("localhost", 12345);
	Stream x;
	x = cast(Stream)conn;
}
```
Errors produced are:
```
testbad.d(17,6): Error: cannot implicitly convert expression conn of type TCPConnection to vibe.core.stream.Stream
testbad.d(22,6): Error: template instance `vibe.core.net.TCPConnection.opCast!(Stream)` does not match template declaration opCast(T)() if (is(T == bool))
```

Edit: The regression appears to have been introduced between 0.8.3-alpha.1 and 0.8.3-alpha.2

**Comment by Herringway** [comment]
After some digging, it looks like this is caused by a default configuration change for vibe-d:core - it now uses the vibe-core configuration by default instead, where TCPConnection is no longer a class inheriting from ConnectionStream, but a struct instead.

This example was reduced from a bit of code for runtime selection of TLS, and it is unclear if this is still supported in any way...

**Comment by s-ludwig** [comment]
This is probably the main breaking change of vibe-core vs. the previous version. There is an implementation that provides dynamic dispatch for `struct` based stream types, but I didn't make it public so far (it's in `vibe.internal.interfaceproxy`) and there are no guarantees that it won't change or be replaced by different solution. It provides two possibilities:

- Wrap a `struct` stream as a `class`/ `interface`: `Stream s = conn.asInterface!Stream;`
- Wrap any stream in a new `struct` based stream: `InterfaceProxy!Stream s = conn.interfaceProxy!Stream;`

Both ways are backwards compatible to the latest `vibe-d:core`, so that it's still possible to switch between the two configurations.

However, because this kind of wrapping produces a certain runtime overhead, whenever possible the preferred way is to avoid the need for dynamic dispatch completely by passing streams as templated types:

```
void foo(S)(S stream) if (isStream!S) { ... }
foo(conn);
```

That way, the compiler can inline function calls throughout the stream pipeline (e.g. when the connection is wrapped by a `TLSStream` and maybe other streams) up to the actual system call in eventcore and there is no overhead for virtual function calls.

In case of dynamic TLS provider selection, this would result in multiple template instantiations, once for each supported TLS implementation.

**Comment by Herringway** [comment]
I see. Managed to work around it, but a breaking change in a patch release caught me off guard. Was the default configuration for vibe-d:core intended to change to vibe-core in this version?

**Comment by s-ludwig** [comment]
Yes, this really is still part of the 0.7.x -> 0.8.x transition, which is just dragged out over the course of a few "patch" releases\*. It's a bit unfortunate that there is no way to have deprecation warnings for sub configurations, because that would have allowed to avoid surprising immediate switching like this.

You can still switch back to the old libevent based implementation using `"subConfigurations": {"vibe-d:core": "libevent"}` to defer the switch. The old `vibe-d:core` module is planned to be finally removed by the end of this year.

\* Not really patch releases - for 0.x.y I usually keep it so that the "y" part denotes incremental changes, which can include minor deprecations or removal of deprecated features (arguable in this case), and "x" denotes bigger and more fundamental changes that cannot follow the usual deprecation process. This will transition to the regular major.minor.patch scheme step by step now for each part of the library (with diet-ng and vibe-core making the start and vibe-http and the serialization module likely following next).

**Comment by Herringway** [comment]
Alright. since it was intended, I'll close this now.
