### ISSUE TITLE
Vibe fails to build on Ubuntu 18.04 (LTS)

### ISSUE THREAD

**Issue by LightBender** [vibe-d/vibe.d#2153]
The default OpenSSL bundled with Ubuntu 18.04 LTS is 1.1.0g which introduces breaking changes from 1.0.x and produces a number of linker errors.

../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/.dub/build/openssl-debug-linux.posix-x86_64-dmd_2079-48332490FF7C779242C4BDF9A2353F52/libvibe-d_tls.a(openssl.o): In function `_D4vibe6stream7openssl18_sharedStaticCtor1FZv':
/home/adamw/Projects/BuildGrid/chimera/../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/vibe/stream/openssl.d:911: undefined reference to `SSL_load_error_strings'
/home/adamw/Projects/BuildGrid/chimera/../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/vibe/stream/openssl.d:912: undefined reference to `SSL_library_init'
/home/adamw/Projects/BuildGrid/chimera/../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/vibe/stream/openssl.d:914: undefined reference to `CRYPTO_num_locks'
/home/adamw/Projects/BuildGrid/chimera/../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/vibe/stream/openssl.d:922: undefined reference to `CRYPTO_set_id_callback'
/home/adamw/Projects/BuildGrid/chimera/../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/vibe/stream/openssl.d:923: undefined reference to `CRYPTO_set_locking_callback'
/home/adamw/Projects/BuildGrid/chimera/../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/vibe/stream/openssl.d:928: undefined reference to `SSL_get_ex_new_index'
../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/.dub/build/openssl-debug-linux.posix-x86_64-dmd_2079-48332490FF7C779242C4BDF9A2353F52/libvibe-d_tls.a(openssl_df_569.o): In function `_D4vibe6stream7openssl14OpenSSLContext6__ctorMFNfEQBwQBu3tls14TLSContextKindEQCxQCvQBb10TLSVersionZ9__lambda3MFNbNeZv':
/home/adamw/Projects/BuildGrid/chimera/../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/vibe/stream/openssl.d:467: undefined reference to `SSLv23_client_method'
/home/adamw/Projects/BuildGrid/chimera/../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/vibe/stream/openssl.d:468: undefined reference to `SSLv23_client_method'
/home/adamw/Projects/BuildGrid/chimera/../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/vibe/stream/openssl.d:472: undefined reference to `SSLv23_client_method'
/home/adamw/Projects/BuildGrid/chimera/../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/vibe/stream/openssl.d:473: undefined reference to `SSLv23_client_method'
/home/adamw/Projects/BuildGrid/chimera/../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/vibe/stream/openssl.d:480: undefined reference to `SSLv23_server_method'
/home/adamw/Projects/BuildGrid/chimera/../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/vibe/stream/openssl.d:481: undefined reference to `SSLv23_server_method'
/home/adamw/Projects/BuildGrid/chimera/../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/vibe/stream/openssl.d:483: undefined reference to `SSLv23_server_method'
/home/adamw/Projects/BuildGrid/chimera/../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/vibe/stream/openssl.d:484: undefined reference to `SSLv23_server_method'
../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/.dub/build/openssl-debug-linux.posix-x86_64-dmd_2079-48332490FF7C779242C4BDF9A2353F52/libvibe-d_tls.a(openssl_df_569.o): In function `_D4vibe6stream7openssl14OpenSSLContext11setDHParamsMFNeAyaZv':
/home/adamw/Projects/BuildGrid/chimera/../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/vibe/stream/openssl.d:722: undefined reference to `get_rfc3526_prime_2048'
../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/.dub/build/openssl-debug-linux.posix-x86_64-dmd_2079-48332490FF7C779242C4BDF9A2353F52/libvibe-d_tls.a(safestack_5ec_449.o): In function `_D6deimos7openssl9safestack__T10SKM_sk_numTSQBqQBm6x509v315GENERAL_NAME_stZ__TQBwZQCaFNbPSQDkQDgQDb__T8STACK_OFTQCrZQoZi':
/home/adamw/Projects/BuildGrid/chimera/../../../.dub/packages/openssl-1.1.6_1.0.1g/openssl/deimos/openssl/safestack.d:140: undefined reference to `sk_num'
../../../.dub/packages/vibe-d-0.8.3/vibe-d/tls/.dub/build/openssl-debug-linux.posix-x86_64-dmd_2079-48332490FF7C779242C4BDF9A2353F52/libvibe-d_tls.a(safestack_5ee_516.o): In function `_D6deimos7openssl9safestack__T12SKM_sk_valueTSQBsQBo6x509v315GENERAL_NAME_stZ__TQByZQCcFNbPSQDmQDiQDd__T8STACK_OFTQCrZQoiZPQDa':
/home/adamw/Projects/BuildGrid/chimera/../../../.dub/packages/openssl-1.1.6_1.0.1g/openssl/deimos/openssl/safestack.d:142: undefined reference to `sk_value'

**Comment by wilzbach** [comment]
What tracking purposes?
The real issues are https://github.com/vibe-d/vibe.d/issues/2053 (detect the OpenSSL version automatically either via dynamic loading, dub support or a clever pregenerate script).

For making OpenSSL 1.1 the default, see https://github.com/vibe-d/vibe.d/pull/2137

(if you disagree that these two issues don't cover you, please reopen or open a new issue with the content they don't address)

**Comment by wilzbach** [comment]
> The default switch to OpenSSL 1.1 is still held back a bit to not break existing installations, it will probably be switched over during the next 3 to 6 months.

It's still problematic, because there are lots of projects testing Vibe.d on Travis.
However, we can introduce some rudimentary auto-detection: https://github.com/vibe-d/vibe.d/pull/2190
