### ISSUE TITLE
Can't compile on win64

### ISSUE THREAD

**Issue by logicfish** [vibe-d/vibe.d#1925]
Can't compile on windows 10 64 bit
dub build --arch=x86_64

```
..\..\..\AppData\Roaming\dub\packages\vibe-d-0.7.32\vibe-d\source\vibe\http\server.d(286,33): Deprecation: alias diet.traits.FilterCallback is deprecated - Use SafeFilterCallback instead.
C:\D\dmd2\windows\bin\..\..\src\druntime\import\core\atomic.d(1065,45): Error: cannot cast expression retVal of type ulong[2] to shared(HTTPServerContext)[] since sizes don't line up
..\..\..\AppData\Roaming\dub\packages\vibe-d-0.7.32\vibe-d\source\vibe\http\server.d(1578,46): Error: template instance core.atomic.atomicLoad!(cast(MemoryOrder)3, shared(HTTPServerContext)[]) error instantiating
```

**Comment by s-ludwig** [comment]
This is a bogus error message, which has been fixed in DMD 2.076.0 as far as I can tell. Unfortunately I didn't notice when this crept in. The master branch (0.8.x) also has removed the atomic operation completely, so that should work on 2.075.x, too.

If there is no particular reason to make this work specifically for 2.075.x, I'd like to resolve this with "wontfix" and save the time required for a workaround.

**Comment by logicfish** [comment]
No reason.

**Comment by s-ludwig** [comment]
Thanks!
