### ISSUE TITLE
ubuntu gdc dub allocator module not found

### ISSUE THREAD

**Issue by paul-eg-c** [vibe-d/vibe.d#1917]
vibe-d package 0.8.1
Ubuntu 17.04 64 bit
compiler gdc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406
dub built 27th Feb 2017
example vibe application package from https://vibed.org/blog/posts/a-scalable-chat-room-service-in-d but without the redis storage parts.
Building with dub gives several failures suggesting that dub.json and/or standard package collection may not be right for this combination.
../../../.dub/packages/vibe-d-0.8.1/vibe-d/utils/vibe/internal/utilallocator.d:3:15: error: module allocator is in file 'std/experimental/allocator.d' which cannot be read
 public import std.experimental.allocator : allocatorObject, CAllocatorImpl, dispose,
Then 'dub'ing in ~/.dub/packages/botan-1.12.9/botan
gives 
...
## Warning for package botan, configuration 32mscoff ##

The following compiler flags have been specified in the package description
file. They are handled by DUB and direct use in packages is discouraged.
Alternatively, you can set the DFLAGS environment variable to pass custom flags
to the compiler, or use one of the suggestions below:

-m32mscoff: Use --arch=x86/--arch=x86_64/--arch=x86_mscoff to specify the target architecture

Running pre-generate commands for botan...
Notice: Botan uses many symbols. Look into switching from ld (bfd) to ld (Gold) linker to reduce link times from >15s to <2s
Performing "debug" build using gdc for x86_64.
botan 1.12.9: building configuration "full"...
Enhanced memory security is enabled.
Memory debugger enabled
source/botan/constants.d:98:73: error: static assert  (BOTAN_HAS_SIMD) is false
 version(SIMD_SSE2) { enum BOTAN_HAS_SIMD_SSE2 = true; 
                                    static assert (BOTAN_HAS_SIMD); }
                                    ^
gdc failed with exit code 1.

I found that mp_types.d has definition of BOTAN_HAS_SIMD for 'version' values: D_SIMD, LDC and else.
It looks as though the version value goes with the else.

Total respect and appreciation.

**Comment by paul-eg-c** [comment]
OK, I've added the allocator directory into .../std/experimental/ and run dub again.
Now getting:
vibe-d:utils 0.8.1: building configuration "library"...
/usr/lib/gcc/x86_64-linux-gnu/6/include/d/std/experimental/allocator/package.d:337:13: error: undefined identifier 'Ternary'
     Ternary owns(void[] b);
             ^
/usr/lib/gcc/x86_64-linux-gnu/6/include/d/std/experimental/allocator/package.d:343:13: error: undefined identifier 'Ternary'
     Ternary resolveInternalPointer(const void* p, ref void[] result);
             ^
/usr/lib/gcc/x86_64-linux-gnu/6/include/d/std/experimental/allocator/package.d:363:13: error: undefined identifier 'Ternary'
     Ternary empty();
             ^
/usr/lib/gcc/x86_64-linux-gnu/6/include/d/std/experimental/allocator/package.d:433:13: error: undefined identifier 'Ternary'
     Ternary owns(void[] b) shared;
             ^
/usr/lib/gcc/x86_64-linux-gnu/6/include/d/std/experimental/allocator/package.d:439:13: error: undefined identifier 'Ternary'
     Ternary resolveInternalPointer(const void* p, ref void[] result) shared;
             ^
/usr/lib/gcc/x86_64-linux-gnu/6/include/d/std/experimental/allocator/package.d:459:13: error: undefined identifier 'Ternary'
     Ternary empty() shared;
             ^
/usr/lib/gcc/x86_64-linux-gnu/6/include/d/std/experimental/allocator/building_blocks/affix_allocator.d:28:12: error: module std.math import 'isPowerOf2' not found
     import std.math : isPowerOf2;
            ^
/usr/lib/gcc/x86_64-linux-gnu/6/include/d/std/experimental/allocator/building_blocks/affix_allocator.d:30:12: error: module std.typecons import 'Ternary' not found
     import std.typecons : Ternary;
            ^
../../../.dub/packages/vibe-d-0.8.1/vibe-d/utils/vibe/utils/hashmap.d:61:25: error: template instance std.experimental.allocator.building_blocks.affix_allocator.AffixAllocator!(AW, int, void) error instantiating
   alias AllocatorType = AffixAllocator!(AW, int);
                         ^
../../../.dub/packages/vibe-d-0.8.1/vibe-d/utils/vibe/internal/memory_legacy.d:178:3: note: instantiated from here: HashMap!(void*, ulong, DefaultHashMapTraits!(void*))
   HashMap!(void*, size_t) m_blocks;
   ^
Hmmm...

**Comment by s-ludwig** [comment]
Not sure what's going on with Botan, but GDC is only supported for the 0.7.x branch (latest release 0.7.32, released a few days ago). There is work being done to let it catch up with the recent D based compiler frontend versions, but until then there are just too many issues to make it work with 0.8.x. I'm pretty sure that there were also some language issues/bugs, so it's not just getting it to compile with Phobos.

**Comment by paul-eg-c** [comment]
Thanks friend. I'll keep watching.

**Comment by Geod24** [comment]
The issue was about a (too) old compiler version. Closing as non actionable.
