### ISSUE TITLE
Build failure from conflicting SO_REUSEPORT definition

### ISSUE THREAD

**Issue by ncoe** [vibe-d/vibe.d#2164]
OS - ubuntu 16.04 docker image.

`/root/.dub/packages/vibe-d-0.7.32/vibe-d/source/vibe/core/drivers/libevent2.d(352,42): Error: vibe.core.drivers.utils.SO_REUSEPORT at /root/.dub/packages/vibe-d-0.7.32/vibe-d/source/vibe/core/drivers/utils.d(53,10) conflicts with core.sys.posix.sys.socket.SO_REUSEPORT at /usr/include/dmd/druntime/import/core/sys/posix/sys/socket.d(306,13)
/root/.dub/packages/vibe-d-0.7.32/vibe-d/source/vibe/core/drivers/threadedfile.d(101,7): Error: constructor calls not allowed in loops or after labels.`

**Comment by wilzbach** [comment]
This has been fixed in 0.8 and I think Sönke is currently working on backporting a few fixes from 0.8 to an 0.7 branch.
Any chance you can use 0.8?
Otherwise try an older compiler

**Comment by ncoe** [comment]
Sorry, I thought I was using the latest already. I will try one of the newer versions and close the issue.

**Comment by s-ludwig** [comment]
As an intermediate step, 0.7.33 has also just been released and works with the latest compiler versions. I'd highly recommend upgrading to 0.8.x, though (possibly starting with 0.8.1 instead of the latest version), as 0.7.x has reached its end-of-life.

**Comment by ncoe** [comment]
Specifying 0.8.3 is sufficient.
